version: '3.2'

services:

  trading-postgres:
    container_name: booking
    image: postgres:15.3-bullseye
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/pgdata
    env_file:
      - .env
    volumes:
      - booking-postgres:/data/pgdata
    ports:
      - "8000:5432"
    expose:
      - "5432"
    restart: unless-stopped



volumes:
  booking-postgres: